#!/usr/bin/env bash
# 
# Attempt at autocompletion script for vboxmanage. This scripts assumes an 
# alias between VBoxManage and vboxmanaage.
#
# Copyright (c) 2012  Thomas Malt <thomas@malt.no>
#


# export VBOXMANAGE_NIC_TYPES

_tmsu() {
    local cur prev opts

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # echo "cur: |$cur|"
    # echo "prev: |$prev|"

    case $prev in 
	-v|--version)
	    return 0
	    ;;

    -v|--verbose)
	    return 0
	    ;;

    -h|--help)
	    return 0
	    ;;

    -D|--database)
	    return 0
	    ;;

    --color)
	    COMPREPLY=($(compgen -W "auto always never" -- ${cur}))
	    return 0
	    ;;


	startvm|list)
	    opts=$(__vboxmanage_$prev)
	    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
	    return 0	    
	    ;;	
	--type)
	    COMPREPLY=($(compgen -W "gui headless" -- ${cur}))
	    return 0
	    ;;
	gui|headless)
	    # Done. no more completion possible
	    return 0
	    ;;
##	tmsu)
##            # In case current is complete command we return emmideatly.
##	    case $cur in
##		startvm|list|controlvm|showvminfo|modifyvm)
##		    COMPREPLY=($(compgen -W "$cur "))
##		    return 0
##		    ;;
##	    esac
	    
	    # echo "Got vboxmanage"
##	    opts=$(__vboxmanage_default)
##	    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
##	    return 0
##	    ;;
##	-q|--nologo)
##	    opts=$(__vboxmanage_default)
##	    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
##	    return 0
##	    ;;
	controlvm|showvminfo|modifyvm)
	    opts=$(__vboxmanage_list_vms)
	    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
	    return 0
	    ;;
	vrde|setlinkstate*)
	    # vrde is a complete subcommand of controlvm
	    opts="on off"
	    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
	    return 0
	    ;;
    esac

}

complete -F _tmsu tmsu
