#!/usr/bin/env bash

GIT_CREDHELPERS="~/.config/git/credhelper.*"
GIT_CRED_STATUS="${YADM_HOOK_DATA}/cred"
GIT_CRED_STATUS="${YADM_HOOK_DATA}/cred"
ls -lad ${YADM_HOOK_DATA}

for filename in $(ls "${GIT_CREDHELPERS}")
do
  echo $filename
done


export GIT_CRYPT_STATUS=crap
if [[ ! -f "${CREDHELPER}" ]]; then
    touch "${GIT_CRED_STATUS}"
fi

git config --file ~/.config/git/credhelper.thor --list
rval=$?
if [[ $? -ne 0 ]]; then 
    touch "${GIT_CRED_STATUS}"
fi

touch "${GIT_CRED_STATUS}"
