#!/usr/bin/env bash

# Get staged files, ignoring deleted files
staged_files=$(git diff --cached --name-only --diff-filter=d)

# Define file groups
shell_files=$(echo "$staged_files" | grep -E '\.sh|(^|/)\..*rc$|\.bash|\.zsh')
code_files=$(echo "$staged_files" | grep -E '\.(js|ts|json|css|md|yaml|yml|html)$')


SHELLCHECK=false
PRETTIER=false
SHFMT=false

function requirements
{
  [[ -x "$(which shellcheck)" ]] && SHELLCHECK=true
  [[ -x "$(which shfmt)" ]] && SHFMT=true
  [[ -x "$(which prettier)" ]] && PRETTIER=true
}

function warning
{
   echo "junk"
}



requirements

echo SHELLCHECK = $SHELLCHECK
echo SHFMT = $SHFMT
echo PRETTIER = $PRETTIER

echo shell_files = $shell_files
echo code_files = $code_files


exit 0
