#!/usr/bin/env bash

# Get staged files, ignoring deleted files
staged_files=$(git diff --cached --name-only --diff-filter=d)

# Define file groups
shell_files=$(echo "$staged_files" | grep -E '\.sh|(^|/)\..*rc$|\.bash|\.zsh')
code_files=$(echo "$staged_files" | grep -E '\.(js|ts|json|css|md|yaml|yml|html)$')


SHELLCHECK=false
PRETTIER=false
SHFMT=false

function requirements
{
  [[ -x "$(which shellcheck)" ]] && SHELLCHECK=true
  [[ -x "$(which shfmt)" ]] && SHFMT=true
  [[ -x "$(which prettier)" ]] && PRETTIER=true
}

function warning
{
   echo "junk"
}



requirements

echo SHELLCHECK = $SHELLCHECK
echo SHFMT = $SHFMT
echo PRETTIER = $PRETTIER

echo shell_files = $shell_files
echo code_files = $code_files

if [[ -n "$shell_files" ]]; then
  echo "Linting shell scripts with shellcheck..."
  for file in $shell_files; do
    shellcheck "$file" || exit 1
  done

  echo "Formatting shell scripts with shfmt..."
  for file in $shell_files; do
    shfmt -w "$file"
    git add "$file"
  done
fi

if [[ -n "$code_files" ]]; then
  echo "Beautifying code files with prettier..."
  for file in $code_files; do
    prettier --write "$file"
    git add "$file"
  done
fi



echo "pre-commit done"

exit 0
