#!/usr/bin/python3
#
import yaml
import os

PATH = os.getcwd()
PATH = "/home/choman/.jira.d"

JIRA = "https://jira.di2e.net"
USERNAME = "chad.homan"
PROJECT = "OADCGS"
PROJECT_SHORT = "di2e"

CONFIG = {}

def read_yaml(CONFIG_YAML):
  with open(CONFIG_YAML) as fp:
    data = yaml.safe_load(fp)

  return data


data = read_yaml(os.path.join(PATH, "custum-commands.yml"))


CONFIG.setdefault("endpoint", JIRA)
CONFIG.setdefault("user", USERNAME)
CONFIG.setdefault("project", PROJECT)
CONFIG.setdefault("editor", "vim")
CONFIG.setdefault("password-source", "gopass")
CONFIG.setdefault("password-name", f"{PROJECT_SHORT}/{USERNAME}")

CONFIG.update(data)


dump = yaml.dump(CONFIG, default_flow_style = False, allow_unicode = True, encoding = None)
print (dump)

##def main():
##  #getgroup()
##  get_yaml()



##if __name__ == "__main__":
##    main()
