#!/bin/bash

grep -q "^flags.*\ hypervisor\ " /proc/cpuinfo
AMIVM=$?

# Go home
cd "$HOME" || echo "can't go to: $HOME"

# setup classes
declare -A class

class["70:85:c2:06:09:a6"]="vboxvdi"
class["08:00:27:17:b9:94"]="funstuff"

# update yadm remote
yadm remote set-url origin https://choman@github.com/choman/dotfiles

# Install/Update yadm submodules
yadm submodule update --init --remote
(cd bashmarks; make install)


##echo "${!class[@]}"
##echo "${class[@]}"
for mac in $(ip addr show | grep ether | awk '{print $2}')
do
    if [ -n "${class[$mac]}" ]; then  
        #echo "$mac => ${class[$mac]}"
        yadm config local.class ${class[$mac]}
    fi
done


# gsettings list-recursively
# update some more system settings
gsettings set com.canonical.indicator.datetime show-day true
gsettings set com.canonical.indicator.datetime show-date true
gsettings set com.canonical.Unity integrated-menus true


# dconf watch /
dconf write /org/compiz/profiles/unity-lowgfx/plugins/core/hsize 2
dconf write /org/compiz/profiles/unity-lowgfx/plugins/core/vsize 2
dconf write /com/canonical/indicator/keyboard/visible false

# really not a vm then do stuff on physical system
if [ $AMIVM -ne 0 ]; then
   dconf write /org/compiz/profiles/unity-lowgfx/plugins/unityshell/launcher-hide-mode 1
fi

dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32
##dconf write /com/canonical/unity/launcher/favorites ['application://org.gnome.Nautilus.desktop', 'application://firefox.desktop', 'application://libreoffice-writer.desktop', 'application://libreoffice-calc.desktop', 'application://libreoffice-impress.desktop', 'application://org.gnome.Software.desktop', 'application://ubuntu-amazon-default.desktop', 'application://unity-control-center.desktop', 'application://virtualbox.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']

##dconf write /org/compiz/profiles/unity/plugins/core/vsize 1
##dconf write /org/compiz/profiles/unity/plugins/core/hsize 5
##dconf write /org/compiz/profiles/unity/plugins/opengl/texture-filter 2
##dconf write /org/compiz/profiles/unity/plugins/unityshell/alt-tab-bias-viewport false


